<?xml version="1.0" encoding="utf-8"?>
<Database Name="DevinDow" Class="ToDoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=sql.bizhostnet.com;Initial Catalog=DevinDow;Persist Security Info=True;User ID=DevinDow" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="old" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Notes" Member="Notes">
    <Type Name="Note">
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TimeFrames" Member="TimeFrames">
    <Type Name="TimeFrame">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TimeFrame_Task" Member="Tasks" ThisKey="ID" OtherKey="TimeFrame" Type="Task" />
    </Type>
  </Table>
  <Table Name="dbo.Tasks" Member="Tasks">
    <Type Name="Task">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TimeFrame" Storage="_Priority" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="Done" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TimeFrame_Task" Member="Priority1" ThisKey="TimeFrame" OtherKey="ID" Type="TimeFrame" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Goals" Member="Goals">
    <Type Name="Goal">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Priority" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Activities" Member="Activities">
    <Type Name="Activity">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Priority" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Priorities" Member="Priorities">
    <Type Name="Priorities">
      <Column Member="ID" Type="System.String" IsPrimaryKey="true" CanBeNull="false" />
      <Column Member="Name" Type="System.String" CanBeNull="false" />
      <Column Member="Priority" Type="System.String" CanBeNull="false" />
      <Column Member="UserName" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Desires" Member="Desires">
    <Type Name="Desires">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Priority" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>